//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dao.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class addPCB
    {
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string Repo { get; set; }
        public string sheft { get; set; }
        public string tray { get; set; }
        public string Approver { get; set; }
        public string Approver_Br { get; set; }
        public Nullable<System.DateTime> Br_date { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Borrower { get; set; }
        public string UserOut { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    }
}
