//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dao.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public string SerialNumber { get; set; }
        public string Model { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorDesc { get; set; }
        public string ErrorDesc2 { get; set; }
    }
}
